"""Initial migration with trends tables

Revision ID: d1fbc9bc34d5
Revises: 
Create Date: 2026-01-31 14:18:13.152145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fbc9bc34d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_references',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('thread_type', sa.String(), nullable=True),
    sa.Column('central_topic', sa.String(), nullable=True),
    sa.Column('article_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('temporal_span', sa.Integer(), nullable=True),
    sa.Column('cluster_density', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('topics',
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('trend_velocity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('topic_name')
    )
    op.create_table('trends',
    sa.Column('trend_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('trend_category', sa.String(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('geo_region', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('trend_id')
    )
    op.create_table('proactive_feed_queue',
    sa.Column('queue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('blocks_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('trend_article_matches',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('infactory_score', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('surfaced_at', sa.DateTime(), nullable=True),
    sa.Column('times_surfaced', sa.Integer(), nullable=True),
    sa.Column('last_surfaced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.trend_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('trend_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('geo_region', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('trend_data')
    op.drop_table('trend_article_matches')
    op.drop_table('proactive_feed_queue')
    op.drop_table('trends')
    op.drop_table('topics')
    op.drop_table('threads')
    op.drop_table('story_references')
    # ### end Alembic commands ###
